# SonarQube scanner configuration for MARAChain
sonar.projectKey=ajmelian_marachain
sonar.organization=ajmelian
sonar.host.url=https://sonarcloud.io
sonar.token=3b41f6b53ed0c2a18a26b0b03d8263d620c27f5d

# Sources (PHP + JS + CSS)
sonar.sources=app/,public/
sonar.exclusions=app/Views/**, app/Database/Seeds/**, app/Language/**, app/Config/Mimes.php, public/assets/plugins/**, public/assets/bundles/**, public/assets/fonts/**, public/assets/images/**, public/assets/js/admin.js, public/assets/js/demo.js, public/assets/js/fullscreen.js, public/assets/js/index.js, public/assets/css/**, public/assets/js/pages/**
sonar.sourceEncoding=UTF-8

# Tests
sonar.tests=tests/
sonar.php.tests.reportPath=build/logs/logfile.xml
sonar.php.coverage.reportPaths=build/logs/clover.xml

# PHP
sonar.php.version=8.5
sonar.php.file.suffixes=php

# JavaScript
sonar.javascript.node.maxspace=4096
